"""
app/api/v1/alerts.py

Alerts API – /api/v1/alerts

Serves real-time and active operational alerts generated by the platform.
Supports category filtering:
- ETA_CHANGED
- SIGNAL_HALT
- HIGH_CONGESTION
- PROPAGATION_RISK
- GPS_STALE
- PLATFORM_PREPARATION
"""

from fastapi import APIRouter, Query, HTTPException
from typing import List, Optional, Dict, Any
from pydantic import BaseModel

from app.services.alert_store import alert_store

router = APIRouter(prefix="/alerts", tags=["Alerts & Notifications"])


class AlertResponse(BaseModel):
    alert_id: str
    category: str
    alert_type: Optional[str] = None
    severity: str
    train_id: Optional[str] = None
    station_code: Optional[str] = None
    section_id: Optional[str] = None
    title: str
    message: str
    is_read: bool = False
    is_active: bool = True
    created_at: str


@router.get("", response_model=List[AlertResponse], summary="List Operational Alerts")
async def list_alerts(
    category: Optional[str] = Query(None, description="Filter by category (e.g., ETA_CHANGED, SIGNAL_HALT, HIGH_CONGESTION, PROPAGATION_RISK, GPS_STALE, PLATFORM_PREPARATION)"),
    active_only: bool = Query(True, description="Return only active alerts"),
    limit: int = Query(50, ge=1, le=200, description="Max alerts to return"),
):
    """
    Retrieve real-time control room alerts generated by delay propagation,
    signal halts, weather disruptions, or significant ETA updates.
    """
    raw_alerts = await alert_store.get_all(active_only=active_only, category=category, limit=limit)
    res = []
    for a in raw_alerts:
        res.append(AlertResponse(
            alert_id=a.get("alert_id", ""),
            category=a.get("category", "INFO"),
            alert_type=a.get("alert_type", a.get("category", "INFO")),
            severity=a.get("severity", "INFO"),
            train_id=a.get("train_id"),
            station_code=a.get("station_code"),
            section_id=a.get("section_id"),
            title=a.get("title", "Operational Alert"),
            message=a.get("message", ""),
            is_read=a.get("is_read", False),
            is_active=a.get("is_active", True),
            created_at=a.get("created_at", ""),
        ))
    return res


@router.post("/{alert_id}/read", summary="Mark Alert as Read")
async def mark_alert_read(alert_id: str):
    """
    Acknowledge and mark a control room alert as read.
    """
    success = await alert_store.mark_read(alert_id)
    if not success:
        raise HTTPException(status_code=404, detail=f"Alert '{alert_id}' not found.")
    return {"status": "success", "alert_id": alert_id, "is_read": True}
